[context.production.environment]
  HUGO_VERSION = "0.156.0"

[build]
  command = "hugo"
  publish = "public"

[[redirects]]
  from = "/index.php/pages/careers"
  to = "/careers/"

[[redirects]]
  from = "/index.php/pages/industries-served"
  to = "/industries/"

[[redirects]]
  from = "/index.php/pages/about-us"
  to = "/about/"

[[redirects]]
  from = "/index.php/pages/facility-list"
  to = "/equipment/"

[[redirects]]
  from = "/index.php/pages/capabilities"
  to = "/capabilities/"

[[redirects]]
  from = "/index.php/pages/gallery"
  to = "/capabilities/"

[[redirects]]
  from = "/index.php/blog/"
  to = "/blog/"

[[redirects]]
  from = "/index.php/news/"
  to = "/blog/"

[[redirects]]
  from = "/index.php/pages/contact"
  to = "/contact/"

[[redirects]]
  from = "/index.php/pages/careers"
  to = "/careers/"

[[redirects]]
  from = "/index.php/frontpage/terms-and-conditions"
  to = "/terms-and-conditions/"