backend:
  name: git-gateway
  branch: master
  repo: Justin-Insight/A-to-Z-Machine

logo_url: https://a-to-z-machine.netlify.app/images/a-to-z-25-year-logo.svg

media_folder: "site/static/images" # Folder where user uploaded files should go
public_folder: ""

collections: # A list of collections the CMS should be able to edit
  - name: "site_settings"
    label: "Site Settings"
    media_folder: "/static/images/"
    public_folder: "/images/"
    editor:
      preview: false
    files:
      - file: "/data/site_settings.yml"
        name: "site_settings"
        label: "Site Settings"
        fields:
          - { label: Logo, name: logo, widget: image }
          - { label: Business Name, name: business_name, widget: string }
          - { label: Phone, name: phone, widget: string }
          - { label: Fax, name: fax, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Address, name: address, widget: text }
          - { label: Google Map URL, name: google_map_url, widget: string }
          - {
              label: "Social Media",
              name: "social_media",
              widget: object,
              fields:
                [
                  {
                    label: "Social",
                    name: "social",
                    widget: list,
                    fields:
                      [
                        { label: "Title", name: "title", widget: string },
                        { label: "URL", name: "link", widget: text },
                      ],
                  },
                ],
            }

  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI, ie.: "New Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - { title: "Title", name: "title", widget: "string" }
      - {
          label: "SEO",
          name: seo,
          widget: object,
          fields:
            [
              { label: "Title", name: "title", widget: string },
              { label: "Description", name: "description", widget: "text" },
              {
                label: "Featured Image",
                name: "featured_image",
                widget: "image",
              },
              {
                label: "Featured Image Alt Text",
                name: "featured_image_alt",
                widget: "string",
              },
            ],
        }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Categories",
          name: "categories",
          widget: "select",
          multiple: true,
          max: 3,
          options: ["Articles", "News"],
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: Title, name: title, widget: string }
          - {
              label: "SEO",
              name: seo,
              widget: object,
              fields:
                [
                  { label: "Title", name: "title", widget: string },
                  { label: "Description", name: "description", widget: "text" },
                  {
                    label: "Featured Image",
                    name: "featured_image",
                    widget: "image",
                  },
                ],
            }
          - {
              label: "Hero Block",
              name: hero,
              widget: object,
              fields:
                [
                  { label: "Heading", name: "heading", widget: string },
                  { label: "Body", name: "body", widget: "text" },
                  { label: "Image", name: "hero_image", widget: "image" },
                  {
                    label: "Image Alt Text",
                    name: "hero_image_alt",
                    widget: string,
                  },
                ],
            }
      - file: "contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Logo, name: logo, widget: image }
          - { label: Body, name: body, widget: markdown }
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
